server:
  port: 9000

spring:
  redis:
    database: 0
    host: 192.168.247.128
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000