server:
  port: 9000

spring:
  datasource:
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      validation-query: SELECT 1 from dual
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      max-wait: 6000
      filter:
        wall,stat,slf4j

      tang-feature:
        url: jdbc:mysql://localhost:3306/tang-feature?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver

      tang-feature1:
        url: jdbc:mysql://localhost:3306/tang-feature1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 192.168.247.128
    #host: 192.168.68.128
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.tangv.feature: DEBUG
